[package]
name = "kondor"
version = "0.1.0"
edition = "2021"
description = "Minimal TUI filesystem cleaner for project artifact directories"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
crossterm = "0.29"
ratatui = "0.29"
rayon = "1.12.0"

[dependencies.kondo-lib]
path = "../kondo-lib"
version = "0.9"
